# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2
jobs:
  build-view:
    docker:
      - image: cimg/node:21.6
    resource_class: large
    environment:
      IMAGE_NAME: bc-view
      STACK_VER: << pipeline.number >>

    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '21.6'
      - node/test:
          test-results-for: jest
      - run:
          name: Build Application
          command: yarn install --frozen-lockfile

      - setup_remote_docker:
          version: '24'
          docker_layer_caching: true
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Package BC-VIEW
                command: |
                  docker buildx create --use
                  docker buildx inspect
                  docker run --rm --privileged tonistiigi/binfmt --install arm64
                  echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
                  docker buildx build --push \
                                      --platform linux/arm64/v8,linux/amd64 \
                                      -t "monowai/$IMAGE_NAME:latest" \
                                      -t "monowai/$IMAGE_NAME:${STACK_VER}" \
                                       ~/project/.
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_package:
    jobs:
      - build-view
