version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build-view:
    docker:
      - image: cimg/node:18.14
    environment:
      IMAGE_NAME: bc-view
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache2-{{ checksum "~/project/yarn.lock" }}
      #      - run:
      #          name: Latest Yarn
      #          command: yarn set version berry
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Test with coverage
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports/junit"
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-cache2-{{ checksum "~/project/yarn.lock" }}
          paths:
            - ./yarn/cache
            - ./yarn/unplugged
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - setup_remote_docker:
          version: 20.10.14
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Package BC-VIEW
                command: |
                  docker buildx create --use
                  docker buildx inspect
                  docker run --rm --privileged tonistiigi/binfmt --install arm64
                  echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
                  docker buildx build --push \
                                      --platform linux/arm64/v8,linux/amd64 \
                                      -t "monowai/$IMAGE_NAME:latest" \
                                       ~/project/.

workflows:
  version: 2
  build_and_stage:
    jobs:
      - build-view
