version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  build-view:
    docker:
      - image: cimg/node:20.12
    resource_class: large
    environment:
      IMAGE_NAME: bc-view
      STACK_VER: << pipeline.number >>
      GIT_BRANCH: << pipeline.git.branch >>
      GIT_COMMIT: << pipeline.git.revision >>

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - node/install:
          install-yarn: true
          node-version: "20.12"
      - run:
          name: Build Application
          command: |
            yarn install --frozen-lockfile
            yarn test:ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          docker_layer_caching: true
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Package BC-VIEW
                command: |
                  SHORT_COMMIT=$(git rev-parse --short $GIT_COMMIT)
                  docker buildx create --use
                  docker buildx inspect
                  docker run --rm --privileged tonistiigi/binfmt --install arm64
                  echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
                  docker buildx build --push \
                                      --platform linux/arm64/v8,linux/amd64 \
                                      --build-arg GIT_BRANCH=$GIT_BRANCH \
                                      --build-arg GIT_COMMIT=$SHORT_COMMIT \
                                      -t "monowai/$IMAGE_NAME:latest" \
                                      -t "monowai/$IMAGE_NAME:${STACK_VER}" \
                                      ~/project/.
workflows:
  build_and_package:
    jobs:
      - build-view
