version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build-view:
    docker:
      - image: circleci/node:14
    environment:
      IMAGE_NAME: bc-view
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache2-{{ checksum "~/project/yarn.lock" }}
      #      - run:
      #          name: Latest Yarn
      #          command: yarn set version berry
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Test with coverage
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports/junit"
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-cache2-{{ checksum "~/project/yarn.lock" }}
          paths:
            - ./yarn/cache
            - ./yarn/unplugged
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Package BC-VIEW
          command: |
            docker build ~/project/. -t monowai/$IMAGE_NAME:latest
            docker tag monowai/$IMAGE_NAME:latest monowai/$IMAGE_NAME:${CIRCLE_BUILD_NUM}
            docker save -o ~/project/$IMAGE_NAME.tar monowai/$IMAGE_NAME
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./bc-view.tar

  docker-publish:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Publish VIEW
          command: |
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
            test -f /tmp/workspace/bc-view.tar
            docker load -i /tmp/workspace/bc-view.tar
            docker push monowai/bc-view

workflows:
  version: 2
  build_and_stage:
    jobs:
      - build-view
      - docker-publish:
          filters:
            branches:
              only: master
          requires:
            - build-view
